name: Build libgit2 XCFrameworks for release
on: [push]
# on: workflow_dispatch
jobs:
  build-libgit2-xcframework:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./build-tools.sh
      - run: ./build-libgit2-framework.sh
      - run: swift package compute-checksum libgit2.xcframework.zip
      - run: swift package compute-checksum Clibgit2.xcframework.zip
      - uses: actions/upload-artifact@v3
        with:
          name: libgit2.xcframework
          path: libgit2.xcframework.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Clibgit2.xcframework
          path: Clibgit2.xcframework.zip

